variables:
  random_state: 42
  test_size: 0.2
  train_size: 0.8
preparation:
  sample_size: 1.0
  columns:
    - InvoiceNo
    - StockCode
    - Description
    - Quantity
    - InvoiceDate
    - UnitPrice
    - CustomerID
    - Country
  types:
    columns:
      InvoiceNo: str
      StockCode: str
      Description: str
      Quantity: int
      InvoiceDate: datetime
      UnitPrice: float
      CustomerID: int
      Country: str
featurization:
  columns:
    - customer_id
    - recency
    - frequency
    - monetary
    - is_churn
  types:
    columns:
      customer_id: int
      recency: float
      frequency: float
      monetary: float
      is_churn: bool
training:
  columns:
    - recency
    # - frequency
    - monetary
  target:
    - is_churn
paths:
  data: 'data/transacciones_retail.csv'
  prepared_data: 'data/prepared_data.csv'
  featurization_data: 'data/featurization_data.csv'
  metrics_model: 'data/metrics_model.json'
  model: 'models/churn_model'
  